import './globals.css'
import Providers from './provider'
import Header from '@/components/common/Header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <div className="mx-auto flex min-h-screen max-w-3xl flex-col border-x border-gray-100 bg-white shadow-2xl">
            <main className="w-full">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  )
}
